name: Deploy to GH Pages
on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installer ShellCheck si besoin
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: cp dist/index.html dist/404.html

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}  # Utiliser un secret sécurisé
          publish_dir: dist
